### ISSUE TITLE
10章で使用するデータの読み込み方がわからない

### ISSUE THREAD

**Issue by mamoru0416** [sakusaku-rich/book-building-knowledge-graphs-ja#12]
9章まではcsvファイルから読み込んでいたと思いますが、10章では見つかりません。
本書10.1の図10-1にてクレジットカード購入履歴のデータを扱っていますが、使用する元データはどこかにありますでしょうか？同様に10.2のスキルマッチングのデータも見つかりません。

**Comment by sakusaku-rich** [comment]
10 章で使用しているデータですが、原著版の「Building Knowledge Graphs: A Practitioner's Guide」でも公開しておらず、日本語版でも公開できない状況です。
本書の出版作業を進めている際に原著者への問い合わせも行ったのですが、データを生成するコードが複雑、且つ生成されるデータ量も多過ぎる[^1]とのことで、現状は公開していないようです。

ご不便をおかけして申し訳ございませんが、実際にデータを使用せずに読み進めていただければと思います。
また代わりのご案内にはなりますが、[Neo4j Sandbox](https://sandbox.neo4j.com/) に存在する Bloom Visual Discovery の Project を起動いただくと、10 章のデータモデルに極めて類似したデータが入った Neo4j を利用できます。本書内の :Person を :AccountHolder などに適宜置き換えていただくと、本書内で紹介しているような怪しいユーザーを見つけることができます。ご参考になれば幸いです。

[^1]: 圧縮した状態で 900MB とのこと。

**Comment by mamoru0416** [comment]
ありがとうございます。原著版にて公開されていないとのこと了解しました。使用するデータが存在しないのは10章だけでよろしかったでしょうか？
また、類似データのほう参考にさせていただきます。

**Comment by sakusaku-rich** [comment]
@mamoru0416 
回答が遅れて申し訳ございません。

10 章以外に 12-16 の articles.csv も存在しません。

逆に公開データを使用している箇所と公開データの所在は以下の通りです。
リスト 11-15: https://github.com/jbarrasa/datasets/blob/master/dep_an/qualified-dependencies.csv
リスト 13-24: https://github.com/globalwordnet/english-wordnet/releases

**Comment by mamoru0416** [comment]
ありがとうございます。
データの所在も教えていただき、大変参考になりました。
